version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  jaeger:
      image: jaegertracing/all-in-one:latest
      ports:
        - "6831:6831/udp"
        - "16686:16686"